name: ticketeer
description: Ticketeer mobile app that allows it's users to buy ticket on different movie sessions
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animations: ^2.0.7
  dio: ^5.1.1
  get_it: ^7.2.0
  auto_route: ^6.3.0
  flutter_otp_text_field: ^1.1.1
  auto_route_generator: ^6.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_feather_icons: ^2.0.0+1
  flutter_spinkit: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  dartz: ^0.10.1
  feather_icons: ^1.2.0
  salomon_bottom_bar: ^3.3.2
  bot_toast: ^4.0.3
  system_theme: ^2.1.0
  shared_preferences: ^2.1.0
  easy_localization: ^3.0.1
  flutter_svg: ^2.0.5
  easy_localization_loader: ^1.0.1+1
  flutter_animate: ^4.1.1+1
  iconsax: ^0.0.8
  logger: ^1.3.0
  shimmer: ^2.0.0
  youtube_player_flutter: ^8.1.2
  flutter_rating_bar: ^4.0.1
  flutter_credit_card: ^3.0.6
  barcode_widget: ^2.0.3
  share_plus: ^6.3.4
  flutter_launcher_icons: ^0.13.1
  intl_phone_field: ^3.1.0
  flutter_native_splash: ^2.2.19

  
flutter_native_splash:
  color: "#121215"
  android_12:
    image: assets/splash_background.png
    color: "#121215"
    icon_background_color: "#121215"



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
 
flutter_launcher_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#1C1C21"
  adaptive_icon_foreground: "assets/icon.png"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - translations/

  fonts:
    - family: Open
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
