name: ticketeer
description: Ticketeer mobile app that allows it's users to buy ticket on different movie sessions
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  animations: ^2.0.7
  dio: ^4.0.6
  file_picker: ^5.2.10
  get_it: ^7.2.0
  auto_route: ^6.3.0
  flutter_otp_text_field: ^1.1.1
  auto_route_generator: ^6.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_feather_icons: ^2.0.0+1
  flutter_spinkit: ^5.1.0
  internet_connection_checker: ^1.0.0+1
  google_nav_bar: ^5.0.6
  dartz: ^0.10.1
  feather_icons: ^1.2.0
  salomon_bottom_bar: ^3.3.2
  bot_toast: ^4.0.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  system_theme: ^2.1.0
  shared_preferences: ^2.1.0
  extra_pedantic: ^3.0.0
  easy_localization: ^3.0.1
  flutter_svg: ^2.0.5
  easy_localization_loader: ^1.0.1+1
  flutter_animate: ^4.1.1+1
  iconsax: ^0.0.8
  logger: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
 


flutter:

  
  uses-material-design: true

  assets:
    - assets/
    - translations/

  fonts:
    - family: Open
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Bold.ttf
          weight: 700
